"""schedule model change

Revision ID: 045b3b080f3a
Revises: 
Create Date: 2026-10-03 12:51:08.528877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '045b3b080f3a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'departments', 'hospitals', ['hospital_id'], ['id'])
    op.alter_column('schedules', 'date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('schedules', 'registration_start',
               existing_type=postgresql.TIME(),
               nullable=True)
    op.alter_column('schedules', 'registration_close',
               existing_type=postgresql.TIME(),
               nullable=True)
    op.alter_column('schedules', 'token_start',
               existing_type=postgresql.TIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('schedules', 'token_start',
               existing_type=postgresql.TIME(),
               nullable=False)
    op.alter_column('schedules', 'registration_close',
               existing_type=postgresql.TIME(),
               nullable=False)
    op.alter_column('schedules', 'registration_start',
               existing_type=postgresql.TIME(),
               nullable=False)
    op.alter_column('schedules', 'date',
               existing_type=sa.DATE(),
               nullable=False)
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'departments', type_='foreignkey')
    # ### end Alembic commands ###
