"""hospital registration no unique removed

Revision ID: 168d9d282a7e
Revises: c5d12f080b00
Create Date: 2026-10-02 08:21:40.906767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '168d9d282a7e'
down_revision: Union[str, Sequence[str], None] = 'c5d12f080b00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('hospitals_registration_no_key'), 'hospitals', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('hospitals_registration_no_key'), 'hospitals', ['registration_no'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
