"""phone unique removed from departments

Revision ID: 3036de1f1407
Revises: fae9fa81955d
Create Date: 2026-10-01 19:40:04.048838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3036de1f1407'
down_revision: Union[str, Sequence[str], None] = 'fae9fa81955d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('departments_phone_key'), 'departments', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('departments_phone_key'), 'departments', ['phone'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
