"""change waiting time to seconds

Revision ID: 4cf475089803
Revises: a1efaa180d70
Create Date: 2026-10-04 16:43:27.128933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4cf475089803'
down_revision: Union[str, Sequence[str], None] = 'a1efaa180d70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tokens', 'waiting_time',
               existing_type=postgresql.TIME(),
               type_=sa.Integer(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tokens', 'waiting_time',
               existing_type=sa.Integer(),
               type_=postgresql.TIME(),
               existing_nullable=True)
    # ### end Alembic commands ###
