"""token model changed

Revision ID: 5df80e18aced
Revises: 64f0155d0996
Create Date: 2026-09-26 21:19:28.880201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '5df80e18aced'
down_revision: Union[str, Sequence[str], None] = '64f0155d0996'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tokens', 'created_at')
    op.drop_column('tokens', 'updated_at')
    op.drop_column('tokens', 'deleted_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('deleted_at', mysql.DATETIME(), nullable=True))
    op.add_column('tokens', sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=False))
    op.add_column('tokens', sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=False))
    # ### end Alembic commands ###
