"""department model change

Revision ID: 8456fbdf2167
Revises: ece83044d2eb
Create Date: 2026-09-30 17:08:10.620588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8456fbdf2167'
down_revision: Union[str, Sequence[str], None] = 'ece83044d2eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('department_no', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('departments', 'department_no')
    # ### end Alembic commands ###
