"""token model changed

Revision ID: a1efaa180d70
Revises: 045b3b080f3a
Create Date: 2026-10-04 13:46:05.295367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a1efaa180d70'
down_revision: Union[str, Sequence[str], None] = '045b3b080f3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('execution_duration', sa.Integer(), nullable=True))
    op.drop_column('tokens', 'actual_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('actual_time', postgresql.TIME(), autoincrement=False, nullable=True))
    op.drop_column('tokens', 'execution_duration')
    # ### end Alembic commands ###
