"""token model updated

Revision ID: a721b207c212
Revises: 5df80e18aced
Create Date: 2026-09-27 08:14:40.364026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a721b207c212'
down_revision: Union[str, Sequence[str], None] = '5df80e18aced'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('patient_name', sa.String(length=255), nullable=False))
    op.add_column('tokens', sa.Column('patient_address', sa.String(length=255), nullable=False))
    op.add_column('tokens', sa.Column('patient_age', sa.Integer(), nullable=False))
    op.add_column('tokens', sa.Column('date', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tokens', 'date')
    op.drop_column('tokens', 'patient_age')
    op.drop_column('tokens', 'patient_address')
    op.drop_column('tokens', 'patient_name')
    # ### end Alembic commands ###
