"""phone unique removed from hospital and users

Revision ID: c5d12f080b00
Revises: 3036de1f1407
Create Date: 2026-10-01 20:03:39.332393

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5d12f080b00'
down_revision: Union[str, Sequence[str], None] = '3036de1f1407'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('hospitals_phone_key'), 'hospitals', type_='unique')
    op.drop_constraint(op.f('users_phone_key'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('users_phone_key'), 'users', ['phone'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('hospitals_phone_key'), 'hospitals', ['phone'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
