"""department room number added

Revision ID: f87d0f497766
Revises: 8456fbdf2167
Create Date: 2026-09-30 17:11:44.101427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f87d0f497766'
down_revision: Union[str, Sequence[str], None] = '8456fbdf2167'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('department_room_no', sa.String(length=50), nullable=True))
    op.drop_column('departments', 'department_no')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('department_no', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('departments', 'department_room_no')
    # ### end Alembic commands ###
