"""hospital model changed

Revision ID: ff158b12f1d1
Revises: 
Create Date: 2026-09-29 12:13:30.259667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff158b12f1d1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hospitals', sa.Column('email', sa.String(length=50), nullable=True))
    op.add_column('hospitals', sa.Column('address', sa.String(length=255), nullable=True))
    op.add_column('hospitals', sa.Column('password', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'hospitals', ['email'])
    op.drop_column('hospitals', 'thumbnail_image')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hospitals', sa.Column('thumbnail_image', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'hospitals', type_='unique')
    op.drop_column('hospitals', 'password')
    op.drop_column('hospitals', 'address')
    op.drop_column('hospitals', 'email')
    # ### end Alembic commands ###
